package com.zuehlke.kotlin.news.data.db.entity

/*
TODO Step 1: Add a NewsArticleEntity (JPA) with the same attributes as the [com.zuehlke.kotlin.news.model.Article]
 Use the JPA annotation @Entity
 Add an autogenerated ID
 */

/*
TODO Step 1: Add an ArticleSourceEntity (JPA) with the same attributes as the [com.zuehlke.kotlin.news.model.ArticleSource]
 Use the JPA annotation @Entity
 */